"use client";
import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "English" | "Tamil" | "Hindi" | "Spanish" | "French";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  English: {
    welcome: "Welcome Back",
    mentor: "AI Career Mentor",
    quick_prompts: "Quick Prompts",
    connect_mentor: "Connect with Mentor",
    gen_code: "Generate Connection Code",
    pairing_code: "Your Pairing Code",
    admin_pair: "Pair New User",
    enter_code: "Enter User Code",
    connect_btn: "Connect Now",
    dashboard: "Intelligence Dashboard",
    execute: "Execute Strategy",
    online: "Online",
    thinking: "Thinking...",
    call_ai: "Call AI Mentor",
    mentor_intro: "I've analyzed your profile. How can we optimize your career today?",
    skill_match: "Skill Match",
    gap_severity: "Gap Severity",
    tech_breadth: "Tech Breadth",
    mobility: "Mobility",
    live_status: "Live System Status",
    calibrated: "Market Calibrated",
    system_config: "System Configuration",
    export_analysis: "Export Analysis",
    notifications: "Live Notifications",
    theme: "Interface Theme",
    dark: "Dark",
    midnight: "Midnight",
    save: "Save Configuration",
    strengths: "Strengths",
    weaknesses: "Weaknesses",
    opportunities: "Opportunities",
    threats: "Threats",
    scan_resume: "Scan Resume",
    skill_lab: "Skill Lab",
    codey_arena: "Codey Arena",
    job_market: "Job Market",
    peer_connect: "Peer Connect",
    total_learners: "Total Learners",
    active_now: "Active Now",
    avg_readiness: "Avg Readiness",
    courses_done: "Courses Done",
    live_sessions: "Live Sessions",
    breakdown: "Breakdown",
    technical_skills: "Technical Skills",
    soft_skills: "Soft Skills",
    domain_expertise: "Domain Expertise",
    recommended_paths: "Recommended Paths",
    ai_matched: "AI-Matched",
    beginner: "Beg",
    intermediate: "Int",
    advanced: "Adv",
    match: "Match",
    jan: "Jan", feb: "Feb", mar: "Mar", apr: "Apr", may: "May", jun: "Jun",
    active_learners: "Active Learners",
    readiness: "Readiness",
    sessions: "Sessions",
    last_active: "Last Active",
    role_readiness: "Role Readiness",
    skill_density: "Skill Density",
    readiness_tiers: "Readiness Tiers",
    dept_perf: "Dept Performance",
    top_performers: "Top Performers",
    xp: "XP",
    ready: "Ready",
    streak: "Streak",
    search_placeholder: "Search by name or email...",
    all_depts: "All Departments",
    sort_by: "Sort By",
    learners_found: "learners found",
    baseline: "Baseline",
    curr_intel: "Current Intel",
    drilldown: "Drilldown Analysis",
    mastery_intel: "Mastery Intelligence",
    proficiency: "Proficiency Level",
    market_demand: "Market Demand",
    learning_path: "Learning Path",
    low: "Low",
    elevated: "Elevated",
    high: "High",
    beginner_full: "Beginner Level",
    intermediate_full: "Intermediate Level",
    advanced_full: "Advanced Level",
    scan_desc: "Upload & analyze profiles",
    lab_desc: "Micro-assessments & quizzes",
    codey_desc: "Coding challenges & tests",
    mentor_desc: "Personalized guidance",
    job_desc: "Matched opportunities",
    gap_desc: "Transformation roadmap",
    peer_desc: "Collaborate with peers",
    pdf_desc: "Full intelligence report with charts",
    json_desc: "Raw skill data for API integration",
    csv_desc: "Tabular data for spreadsheet analysis",
    goal: "Goal",
    live_session: "Live Session",
    confidence: "Confidence",
    clarity: "Clarity",
    technical: "Technical",
    ai_interviewer: "AI Interviewer",
    interview_prompt: "Focus on efficiency and structural clarity in your response. I am analyzing your technical depth against enterprise benchmarks.",
    velocity_score: "Velocity Score",
    learning_sessions: "Learning Sessions",
    explore_expert: "Explore Expert Path",
    compare_benchmarks: "Compare Benchmarks",
    initialize_pathway: "Initialize Pathway",
    strategy_title: "Prescriptive Transformation Strategy",
    workforce_resilience: "Workforce Resilience",
    month: "Month",
    export: "Export",
    config: "Config",
    active: "Active",
    dossier: "Dossier",
    live: "Live",
    complete: "Complete",
    deploying: "Deploying",
    calibrating: "Calibrating",
    python_demand: "Python demand +12% in Chennai",
    cloud_architecture: "Cloud Architecture roles up 8% Globally",
    ai_matched_desc: "AI-matched courses mapped to your skill gaps",
    explore_10k_courses: "Explore 10,000+ Courses",
    world_class_learning: "World-class learning from top universities",
    browse_coursera: "Browse Coursera",
    learn_more: "Learn More",
    courses: "Courses",
    weeks_12: "12 weeks",
    skills: "Skills",
    strategy_desc_1: "AI-identified learning pathway to elevate your",
    strategy_desc_2: ". Master ",
    strategy_desc_3: " to unlock new opportunities in ",
    overview: "Overview",
    skill_deep_dive: "Skill Deep Dive",
    growth_velocity: "Growth Velocity",
    skill_velocity: "Skill Velocity",
    acquisition_rate_6_months: "Acquisition rate • 6 months",
    structural_gaps: "Structural Gaps",
    gap: "gap",
    severity: "Severity",
    ai_matched_courses: "AI-matched courses mapped to your skill gaps",
    explore_courses: "Explore 10,000+ Courses",
    velocity_desc: "Skill acquisition trajectory & learning sessions",
    quick_actions: "Quick Actions",
    courses_recommended: "courses recommended",
    admin_panel: "ADMIN PANEL",
    learner_dashboard: "Learner Dashboard",
    weekly_activity: "Weekly Activity",
    performance_trends: "Performance Trends",
    scan: "Scan",
    jobs: "Jobs",
    connect: "Connect",
    codey: "Codey",
    admin: "Admin",
    weekly_activity_desc: "Logins, course progress & lab sessions this week",
    skills_distribution: "Skills Distribution",
    workforce_readiness: "Workforce Readiness Overview",
    role_affinity: "Role Affinity",
    top_learning_tracks: "Top Learning Tracks",
    learner_growth: "Learner Growth (12 Months)",
    lab: "Lab",
    code: "Code",
    xp: "XP",
    streak: "Streak",
    logins: "Logins",
    course_progress: "Course Progress",
    lab_sessions: "Lab Sessions",
    role_readiness_dist: "Role readiness distribution across the workforce",
    export_complete: "Export Complete",
    export_complete_desc: "Your intelligence report has been generated.",
    compiling_report: "Compiling Intelligence Report...",
    aggregating_data: "Aggregating skill vectors and SWOT matrices",
    export_fmt: "Export",
    default_benchmark: "Default Benchmark",
    realtime_notifications: "Real-time Notifications",
    notifications_desc: "Alerts for skill market shifts",
    interface_theme: "Interface Theme",
    theme_desc: "Dashboard visual mode",
    ai_news_hub: "Intelligence Update Hub",
    latest_intel: "Global AI Intelligence",
    read_full_report: "Read Intel Report",
    source: "Intelligence Source",
    minutes_ago: "min ago",
    hours_ago: "h ago",
  },
  Tamil: {
    welcome: "மீண்டும் வருக",
    mentor: "AI தொழில் வழிகாட்டி",
    quick_prompts: "விரைவான தூண்டுதல்கள்",
    connect_mentor: "வழிகாட்டியுடன் இணையுங்கள்",
    gen_code: "இணைப்பு குறியீட்டை உருவாக்கு",
    pairing_code: "உங்கள் இணைப்புக் குறியீடு",
    admin_pair: "புதிய பயனரை இணைக்கவும்",
    enter_code: "பயனர் குறியீட்டை உள்ளிடவும்",
    connect_btn: "இப்போது இணைக்கவும்",
    dashboard: "புத்திசாலித்தனமான டேஷ்போர்டு",
    execute: "மூலோபாயத்தை செயல்படுத்தவும்",
    online: "ஆன்லைனில்",
    thinking: "சிந்திக்கிறது...",
    call_ai: "AI வழிகாட்டியை அழைக்கவும்",
    mentor_intro: "உங்கள் சுயவிவரத்தை நான் பகுப்பாய்வு செய்துள்ளேன். இன்று உங்கள் வாழ்க்கையை எவ்வாறு மேம்படுத்தலாம்?",
    skill_match: "திறன் பொருத்தம்",
    gap_severity: "இடைவெளி தீவிரம்",
    tech_breadth: "தொழில்நுட்ப அகலம்",
    mobility: "இடம்பெயர்வு",
    live_status: "நேரடி கணினி நிலை",
    calibrated: "சந்தை அளவீடு செய்யப்பட்டது",
    system_config: "கணினி கட்டமைப்பு",
    export_analysis: "பகுப்பாய்வை ஏற்றுமதி செய்",
    notifications: "நேரடி அறிவிப்புகள்",
    theme: "இடைமுக தீம்",
    dark: "இருண்ட",
    midnight: "நள்ளிரவு",
    save: "கட்டமைப்பைச் சேமி",
    strengths: "பலங்கள்",
    weaknesses: "பலவீனங்கள்",
    opportunities: "வாய்ப்புகள்",
    threats: "அச்சுறுத்தல்கள்",
    scan_resume: "சுயவிவர ஆய்வு",
    skill_lab: "திறன் ஆய்வகம்",
    codey_arena: "கோடி அரங்கம்",
    job_market: "வேலை சந்தை",
    peer_connect: "சகாக்களுடன் தொடர்பு",
    total_learners: "மொத்த மாணவர்கள்",
    active_now: "இப்போது செயலில்",
    avg_readiness: "சராசரி தயார்நிலை",
    courses_done: "முடிக்கப்பட்ட படிப்புகள்",
    live_sessions: "நேரடி அமர்வுகள்",
    breakdown: "விளக்கம்",
    technical_skills: "தொழில்நுட்ப திறன்கள்",
    soft_skills: "மென் திறன்கள்",
    domain_expertise: "துறை நிபுணத்துவம்",
    recommended_paths: "பரிந்துரைக்கப்பட்ட பாதைகள்",
    ai_matched: "AI-பொருத்தம்",
    beginner: "தொடக்க",
    intermediate: "இடைநிலை",
    advanced: "மேம்பட்ட",
    match: "பொருத்தம்",
    jan: "ஜன", feb: "பிப்", mar: "மார்", apr: "ஏப்", may: "மே", jun: "ஜூன்",
    active_learners: "செயலில் உள்ள மாணவர்கள்",
    readiness: "தயார்நிலை",
    sessions: "அமர்வுகள்",
    last_active: "கடைசியாக செயலில்",
    role_readiness: "பணி தயார்நிலை",
    skill_density: "திறன் அடர்த்தி",
    readiness_tiers: "தயார்நிலை நிலைகள்",
    dept_perf: "துறை செயல்திறன்",
    top_performers: "சிறந்த மாணவர்கள்",
    xp: "அனுபவம் (XP)",
    ready: "தயார்",
    streak: "தொடர்ச்சி",
    search_placeholder: "பெயர் அல்லது மின்னஞ்சல் மூலம் தேடுக...",
    all_depts: "அனைத்து துறைகளும்",
    sort_by: "வரிசைப்படுத்து",
    learners_found: "மாணவர்கள் கண்டறியப்பட்டனர்",
    baseline: "அடிப்படை",
    curr_intel: "தற்போதைய நுண்ணறிவு",
    drilldown: "விரிவான ஆய்வு",
    mastery_intel: "நிபுணத்துவ நுண்ணறிவு",
    proficiency: "திறமை நிலை",
    market_demand: "சந்தை தேவை",
    learning_path: "கற்றல் பாதை",
    low: "குறைவாக",
    elevated: "அதிகமாக",
    high: "மிக அதிகமாக",
    beginner_full: "தொடக்க நிலை",
    intermediate_full: "இடைநிலை நிலை",
    advanced_full: "மேம்பட்ட நிலை",
    scan_desc: "சுயவிவரங்களை பதிவேற்றி பகுப்பாய்வு செய்யுங்கள்",
    lab_desc: "குறு மதிப்பீடுகள் மற்றும் வினாடி வினாக்கள்",
    codey_desc: "குறியீட்டு சவால்கள் மற்றும் தேர்வுகள்",
    mentor_desc: "தனிப்பயனாக்கப்பட்ட வழிகாட்டுதல்",
    job_desc: "பொருத்தமான வேலை வாய்ப்புகள்",
    gap_desc: "மாற்றத்திற்கான வழிகாட்டி",
    peer_desc: "சகாக்களுடன் ஒத்துழைப்பு",
    pdf_desc: "விளக்கப்படங்களுடன் கூடிய முழு அறிக்கை",
    json_desc: "API ஒருங்கிணைப்புக்கான தரவு",
    csv_desc: "தரவு விரிதாள் பகுப்பாய்விற்கான தரவு",
    goal: "இலக்கு",
    live_session: "நேரடி அமர்வு",
    confidence: "நம்பிக்கை",
    clarity: "தெளிவு",
    technical: "தொழில்நுட்பம்",
    ai_interviewer: "AI நேர்காணல் செய்பவர்",
    interview_prompt: "உங்கள் பதிலில் செயல்திறன் மற்றும் கட்டமைப்புத் தெளிவில் கவனம் செலுத்துங்கள். நிறுவனத்தின் அளவுகோல்களுடன் உங்கள் தொழில்நுட்ப ஆழத்தை நான் பகுப்பாய்வு செய்கிறேன்.",
    velocity_score: "வேக மதிப்பெண்",
    learning_sessions: "கற்றல் அமர்வுகள்",
    explore_expert: "நிபுணர் பாதையை ஆராயுங்கள்",
    compare_benchmarks: "மதிப்பீடுகளை ஒப்பிடுக",
    initialize_pathway: "பாதையைத் தொடங்கவும்",
    strategy_title: "பரிந்துரைக்கப்பட்ட மாற்ற உத்தி",
    workforce_resilience: "பணியாளர் நெகிழ்ச்சி",
    month: "மாதம்",
    export: "ஏற்றுமதி",
    config: "கட்டமைப்பு",
    active: "செயலில்",
    dossier: "ஆவணம்",
    live: "நேரடி",
    complete: "நிறைவு",
    deploying: "பயன்படுத்தல்",
    calibrating: "அளவீடு",
    python_demand: "சென்னையில் பைதான் தேவை +12% அதிகரித்துள்ளது",
    cloud_architecture: "கிளவுட் ஆர்கிடெக்சர் பணிகள் உலகளவில் 8% அதிகரித்துள்ளன",
    ai_matched_desc: "உங்கள் திறன் இடைவெளிகளுக்கு வரைபடமாக்கப்பட்ட AI-பொருத்தமான படிப்புகள்",
    explore_10k_courses: "10,000+ படிப்புகளை ஆராயுங்கள்",
    world_class_learning: "சிறந்த பல்கலைக்கழகங்களில் இருந்து உலகத்தரம் வாய்ந்த கற்றல்",
    browse_coursera: "கோர்செராவை உலாவுக",
    learn_more: "மேலும் அறிக",
    courses: "படிப்புகள்",
    weeks_12: "12 வாரங்கள்",
    skills: "திறன்கள்",
    strategy_desc_1: "உங்கள் ",
    strategy_desc_2: " மேம்படுத்த AI-அடையாளம் காணப்பட்ட கற்றல் பாதை. ",
    strategy_desc_3: " ஆகியவற்றில் தேர்ச்சி பெறுவதன் மூலம் ",
    strategy_desc_4: "க்குள் புதிய வாய்ப்புகளைப் பெறலாம்.",
    overview: "மேலோட்டம்",
    skill_deep_dive: "திறன் ஆழமான ஆய்வு",
    growth_velocity: "வளர்ச்சி வேகம்",
    skill_velocity: "திறன் வேகம்",
    acquisition_rate_6_months: "கையகப்படுத்துதல் விகிதம் • 6 மாதங்கள்",
    structural_gaps: "கட்டமைப்பு இடைவெளிகள்",
    gap: "இடைவெளி",
    severity: "தீவிரம்",
    ai_matched_courses: "உங்கள் திறன் இடைவெளிகளுக்கு வரைபடமாக்கப்பட்ட AI-பொருத்தமான படிப்புகள்",
    explore_courses: "10,000+ படிப்புகளை ஆராயுங்கள்",
    velocity_desc: "திறன் கையகப்படுத்தல் பாதை மற்றும் கற்றல் அமர்வுகள்",
    quick_actions: "விரைவான செயல்கள்",
    courses_recommended: "படிப்புகள் பரிந்துரைக்கப்படுகின்றன",
    admin_panel: "நிர்வாக குழு",
    learner_dashboard: "மாணவர் டாஷ்போர்டு",
    weekly_activity: "வாராந்திர செயல்பாடு",
    performance_trends: "செயல்திறன் போக்குகள்",
    scan: "ஸ்கேன்",
    jobs: "வேலைகள்",
    connect: "இணைப்பு",
    codey: "கோடி",
    admin: "நிர்வாகம்",
    weekly_activity_desc: "இந்த வார உள்நுழைவுகள், பாடத்திட்ட முன்னேற்றம் மற்றும் ஆய்வக அமர்வுகள்",
    skills_distribution: "திறன் விநியோகம்",
    workforce_readiness: "பணியாளர் தயார்நிலை மேலோட்டம்",
    role_affinity: "பணி ஈர்ப்பு",
    top_learning_tracks: "சிறந்த கற்றல் தடங்கள்",
    learner_growth: "மாணவர் வளர்ச்சி (12 மாதங்கள்)",
    lab: "ஆய்வகம்",
    code: "குறியீடு",
    xp: "அனுபவம் (XP)",
    streak: "தொடர்ச்சி",
    logins: "உள்நுழைவுகள்",
    course_progress: "பாடத்திட்ட முன்னேற்றம்",
    lab_sessions: "ஆய்வக அமர்வுகள்",
    role_readiness_dist: "பணியாளர்கள் மத்தியில் பணி தயார்நிலை விநியோகம்",
    export_complete: "ஏற்றுமதி முடிந்தது",
    export_complete_desc: "உங்கள் புத்திசாலித்தன அறிக்கை உருவாக்கப்பட்டுள்ளது.",
    compiling_report: "புத்திசாலித்தன அறிக்கையை தொகுக்கிறது...",
    aggregating_data: "திறன் வெக்டர்கள் மற்றும் SWOT மேட்ரிக்ஸை ஒருங்கிணைத்தல்",
    export_fmt: "ஏற்றுமதி",
    default_benchmark: "இயல்புநிலை அளவுகோல்",
    realtime_notifications: "நேரடி அறிவிப்புகள்",
    notifications_desc: "திறன் சந்தை மாற்றங்களுக்கான விழிப்பூட்டல்கள்",
    interface_theme: "இடைமுக தீம்",
    theme_desc: "டாஷ்போர்டு காட்சி முறை",
    ai_news_hub: "AI உளவுத்துறை புதுப்பிப்புகள்",
    latest_intel: "உலகளாவிய AI தகவல்கள்",
    read_full_report: "முழு அறிக்கையையும் படிக்கவும்",
    source: "தகவல் ஆதாரம்",
    minutes_ago: "நிமிடங்களுக்கு முன்",
    hours_ago: "மணிநேரங்களுக்கு முன்",
  },
  Hindi: {
    welcome: "स्वागत है",
    mentor: "AI करियर मेंटर",
    ai_news_hub: "AI न्यूज़ हब",
    latest_intel: "वैश्विक AI समाचार",
    read_full_report: "पूरी रिपोर्ट पढ़ें",
    source: "स्रोत",
  },
  Spanish: {},
  French: {},
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("English");

  useEffect(() => {
    const saved = localStorage.getItem("ss_lang") as Language;
    if (saved && translations[saved]) {
      setLanguage(saved);
    }
  }, []);

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("ss_lang", lang);
  };

  const t = (key: string) => {
    return translations[language][key] || translations["English"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
